# ----------------------------
# Makefile Options
# ----------------------------

NAME = AESOP
DESCRIPTION = "Neural Story Generator"
COMPRESSED = NO
ARCHIVED = YES

CFLAGS = -Wall -Wextra -Oz $(EXTRA_CFLAGS)
ASFLAGS =
LTO = YES
HAS_PRINTF = NO

# ----------------------------

include $(shell cedev-config --makefile)
